In [27]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

<h2>Preparing the data</h2>

In [3]:
import kagglehub

In [4]:
path = kagglehub.dataset_download("fanbyprinciple/iot-device-identification")

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.11)

In [5]:
data_train = pd.read_csv(path + "/iot_device_train.csv")
data_test = pd.read_csv(path + "/iot_device_test.csv")

In [6]:
data_all = pd.concat([data_train, data_test], axis=0, ignore_index=True)

In [10]:
data_all = data_all.sample(frac=1, random_state=42).reset_index(drop=True)

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()
data_all['device_category_label'] = le.fit_transform(data_all['device_category'])

In [39]:
data_all['device_category_label']

0       3
1       0
2       8
3       8
4       4
       ..
1895    2
1896    3
1897    2
1898    5
1899    2
Name: device_category_label, Length: 1900, dtype: int32

In [15]:
data_all.columns

Index(['ack', 'ack_A', 'ack_B', 'bytes', 'bytes_A', 'bytes_A_B_ratio',
       'bytes_B', 'ds_field_A', 'ds_field_B', 'duration',
       ...
       'suffix_is_com', 'suffix_is_com.sg', 'suffix_is_else',
       'suffix_is_empty_char_value', 'suffix_is_googleapis.com',
       'suffix_is_net', 'suffix_is_org', 'suffix_is_unresolved',
       'device_category', 'device_category_label'],
      dtype='object', length=299)

In [19]:
corr = data_all.drop(axis=0, columns='device_category').corr().abs()['device_category_label'].sort_values(ascending=False)

In [20]:
print(corr)

device_category_label       1.000000
reset                       0.404447
reset_A                     0.396896
ttl_B_thirdQ                0.345751
ttl_B_median                0.338601
                              ...
suffix_is_co.il                  NaN
suffix_is_com.sg                 NaN
suffix_is_googleapis.com         NaN
suffix_is_net                    NaN
suffix_is_org                    NaN
Name: device_category_label, Length: 298, dtype: float64

In [43]:
dummies = pd.get_dummies(data_all['device_category'], dtype=int)
print(dummies)

      TV  baby_monitor  lights  motion_sensor  security_camera  \
0      0             0       0              1                0
1      1             0       0              0                0
2      0             0       0              0                0
3      0             0       0              0                0
4      0             0       0              0                1
...   ..           ...     ...            ...              ...
1895   0             0       1              0                0
1896   0             0       0              1                0
1897   0             0       1              0                0
1898   0             0       0              0                0
1899   0             0       1              0                0

      smoke_detector  socket  thermostat  watch  water_sensor
0                  0       0           0      0             0
1                  0       0           0      0             0
2                  0       0           0      1             0
3                  0       0           0      1             0
4                  0       0           0      0             0
...              ...     ...         ...    ...           ...
1895               0       0           0      0             0
1896               0       0           0      0             0
1897               0       0           0      0             0
1898               1       0           0      0             0
1899               0       0           0      0             0

[1900 rows x 10 columns]

In [44]:
categories = dummies.columns.tolist()
print(categories)

['TV', 'baby_monitor', 'lights', 'motion_sensor', 'security_camera', 'smoke_detector', 'socket', 'thermostat', 'watch', 'water_sensor']

In [24]:
data_X = data_all.drop(columns=['device_category', 'device_category_label'])
print(data_X)

        ack  ack_A  ack_B    bytes  bytes_A  bytes_A_B_ratio  bytes_B  \
0        48     18     30     1382      654         0.898350      728
1         9      5      5     1213      743         1.142203      668
2         9      5      5     1213      743         1.806874      668
3         9      5      5     1213      743         1.806874      668
4        12      6      6     1548      645         0.714285      903
...     ...    ...    ...      ...      ...              ...      ...
1895      0      0      0      240        0         0.000000      240
1896  24718  12359  12359  1483080   741540         1.000000   741540
1897      0      0      0      240        0         0.000000      240
1898     14      7      7     2411     1317         1.203838     1094
1899      0      0      0      240        0         0.000000      240

      ds_field_A  ds_field_B    duration  ...  suffix_is_cloudfront.net  \
0              0           0      1.7060  ...                         0
1              0           0      0.7328  ...                         0
2              0           0      1.5756  ...                         0
3              0           0      1.5756  ...                         0
4              0           0      0.8530  ...                         0
...          ...         ...         ...  ...                       ...
1895           0          64      1.4991  ...                         0
1896           0           0  58432.6504  ...                         0
1897           0          64      1.5739  ...                         0
1898           0           0      2.9601  ...                         0
1899           0          64      1.4989  ...                         0

      suffix_is_co.il  suffix_is_com  suffix_is_com.sg  suffix_is_else  \
0                   0              0                 0               0
1                   0              0                 0               1
2                   0              0                 0               1
3                   0              0                 0               1
4                   0              0                 0               0
...               ...            ...               ...             ...
1895                0              0                 0               0
1896                0              0                 0               0
1897                0              0                 0               1
1898                0              0                 0               0
1899                0              0                 0               0

      suffix_is_empty_char_value  suffix_is_googleapis.com  suffix_is_net  \
0                              0                         0              0
1                              0                         0              0
2                              0                         0              0
3                              0                         0              0
4                              0                         0              0
...                          ...                       ...            ...
1895                           1                         0              0
1896                           1                         0              0
1897                           0                         0              0
1898                           1                         0              0
1899                           1                         0              0

      suffix_is_org  suffix_is_unresolved
0                 0                     1
1                 0                     0
2                 0                     0
3                 0                     0
4                 0                     1
...             ...                   ...
1895              0                     0
1896              0                     0
1897              0                     0
1898              0                     0
1899              0                     0

[1900 rows x 297 columns]

In [45]:
corr_per_category = []
for category in categories:
    corr_per_category.append(pd.concat([data_X, dummies[category]], axis=1).corr().abs()[category].sort_values(ascending=False))

In [48]:
corr_per_category_top = [corr_per_category[i].head(10) for i in range(len(corr_per_category))]
print(corr_per_category_top)

[TV              1.000000
ttl_B_min       0.496075
reset_B         0.370424
ttl_A_avg       0.308538
ttl_A_firstQ    0.308538
ttl_A_max       0.308538
ttl_A_median    0.308538
ttl_A_min       0.308538
ttl_A_thirdQ    0.308538
ttl_B_median    0.287217
Name: TV, dtype: float64, baby_monitor             1.000000
reset_A                  0.660903
reset                    0.565487
ttl_B_stdev              0.517958
ttl_B_max                0.482812
ttl_B_thirdQ             0.469859
ttl_B_avg                0.434098
ttl_B_firstQ             0.424674
ttl_B_median             0.421507
packet_size_B_entropy    0.404990
Name: baby_monitor, dtype: float64, lights                         1.000000
packet_inter_arrivel_min       0.581965
B_port_is_8080                 0.577076
packet_inter_arrivel_firstQ    0.575378
ttl_min                        0.574552
ttl_firstQ                     0.573342
ds_field_B                     0.572415
packet_inter_arrivel_A_min     0.561040
packet_inter_arrivel_median    0.551864
ttl_entropy                    0.528918
Name: lights, dtype: float64, motion_sensor                   1.000000
domain_is_else                  0.736364
http_count_user_agents          0.725062
is_http                         0.725062
http_count_host                 0.725062
http_count_req_content_type     0.725062
http_has_req_content_type       0.725062
http_has_resp_content_type      0.725062
http_has_user_agent             0.725062
http_count_resp_content_type    0.724871
Name: motion_sensor, dtype: float64, security_camera                     1.000000
ssl_ratio_client_elliptic_curves    0.393544
ttl_A_avg                           0.308538
ttl_A_firstQ                        0.308538
ttl_A_max                           0.308538
ttl_A_median                        0.308538
ttl_A_min                           0.308538
ttl_A_thirdQ                        0.308538
ttl_median                          0.269020
ttl_max                             0.249434
Name: security_camera, dtype: float64, smoke_detector                1.000000
B_port_is_11095               0.687184
ttl_var                       0.550083
ttl_stdev                     0.522448
packet_inter_arrivel_B_min    0.421438
ttl_median                    0.389614
ttl_A_median                  0.384507
ttl_A_firstQ                  0.384507
ttl_A_thirdQ                  0.384507
ttl_A_min                     0.384507
Name: smoke_detector, dtype: float64, socket                         1.000000
B_port_is_8080                 0.577076
packet_inter_arrivel_firstQ    0.575033
ttl_min                        0.574552
ttl_firstQ                     0.573342
packet_inter_arrivel_min       0.573135
ds_field_B                     0.572415
packet_inter_arrivel_median    0.556265
packet_inter_arrivel_A_min     0.552114
ttl_entropy                    0.528918
Name: socket, dtype: float64, thermostat                       1.000000
packet_size_A_thirdQ             0.540421
ssl_req_bytes_stdev              0.493405
packet_size_A_var                0.484169
ttl_max                          0.459357
ssl_count_client_ciphersuites    0.439982
packet_size_A_stdev              0.419881
ssl_dom_server_name_alexaRank    0.410466
ttl_thirdQ                       0.403659
packet_size_A_avg                0.402770
Name: thermostat, dtype: float64, watch                   1.000000
reset_B                 0.374432
ttl_thirdQ              0.374031
packet_size_B_thirdQ    0.349233
packet_size_B_avg       0.325506
ttl_A_thirdQ            0.308538
ttl_A_min               0.308538
ttl_A_median            0.308538
ttl_A_max               0.308538
ttl_A_firstQ            0.308538
Name: watch, dtype: float64, water_sensor                   1.000000
ttl_min                        0.364884
ttl_firstQ                     0.363620
B_port_is_8080                 0.353626
ds_field_B                     0.350548
packet_inter_arrivel_firstQ    0.350330
packet_inter_arrivel_min       0.342999
packet_inter_arrivel_median    0.341444
packet_inter_arrivel_A_min     0.328024
packets_A_B_ratio              0.323405
Name: water_sensor, dtype: float64]

In [81]:
# turn corr_per_category into a dictionary
corr_per_category_top_dict = {}
for i in range(len(categories)):
    corr_per_category_top_dict[categories[i]] = corr_per_category_top[i]
print(corr_per_category_top_dict)

{'TV': TV              1.000000
ttl_B_min       0.496075
reset_B         0.370424
ttl_A_avg       0.308538
ttl_A_firstQ    0.308538
ttl_A_max       0.308538
ttl_A_median    0.308538
ttl_A_min       0.308538
ttl_A_thirdQ    0.308538
ttl_B_median    0.287217
Name: TV, dtype: float64, 'baby_monitor': baby_monitor             1.000000
reset_A                  0.660903
reset                    0.565487
ttl_B_stdev              0.517958
ttl_B_max                0.482812
ttl_B_thirdQ             0.469859
ttl_B_avg                0.434098
ttl_B_firstQ             0.424674
ttl_B_median             0.421507
packet_size_B_entropy    0.404990
Name: baby_monitor, dtype: float64, 'lights': lights                         1.000000
packet_inter_arrivel_min       0.581965
B_port_is_8080                 0.577076
packet_inter_arrivel_firstQ    0.575378
ttl_min                        0.574552
ttl_firstQ                     0.573342
ds_field_B                     0.572415
packet_inter_arrivel_A_min     0.561040
packet_inter_arrivel_median    0.551864
ttl_entropy                    0.528918
Name: lights, dtype: float64, 'motion_sensor': motion_sensor                   1.000000
domain_is_else                  0.736364
http_count_user_agents          0.725062
is_http                         0.725062
http_count_host                 0.725062
http_count_req_content_type     0.725062
http_has_req_content_type       0.725062
http_has_resp_content_type      0.725062
http_has_user_agent             0.725062
http_count_resp_content_type    0.724871
Name: motion_sensor, dtype: float64, 'security_camera': security_camera                     1.000000
ssl_ratio_client_elliptic_curves    0.393544
ttl_A_avg                           0.308538
ttl_A_firstQ                        0.308538
ttl_A_max                           0.308538
ttl_A_median                        0.308538
ttl_A_min                           0.308538
ttl_A_thirdQ                        0.308538
ttl_median                          0.269020
ttl_max                             0.249434
Name: security_camera, dtype: float64, 'smoke_detector': smoke_detector                1.000000
B_port_is_11095               0.687184
ttl_var                       0.550083
ttl_stdev                     0.522448
packet_inter_arrivel_B_min    0.421438
ttl_median                    0.389614
ttl_A_median                  0.384507
ttl_A_firstQ                  0.384507
ttl_A_thirdQ                  0.384507
ttl_A_min                     0.384507
Name: smoke_detector, dtype: float64, 'socket': socket                         1.000000
B_port_is_8080                 0.577076
packet_inter_arrivel_firstQ    0.575033
ttl_min                        0.574552
ttl_firstQ                     0.573342
packet_inter_arrivel_min       0.573135
ds_field_B                     0.572415
packet_inter_arrivel_median    0.556265
packet_inter_arrivel_A_min     0.552114
ttl_entropy                    0.528918
Name: socket, dtype: float64, 'thermostat': thermostat                       1.000000
packet_size_A_thirdQ             0.540421
ssl_req_bytes_stdev              0.493405
packet_size_A_var                0.484169
ttl_max                          0.459357
ssl_count_client_ciphersuites    0.439982
packet_size_A_stdev              0.419881
ssl_dom_server_name_alexaRank    0.410466
ttl_thirdQ                       0.403659
packet_size_A_avg                0.402770
Name: thermostat, dtype: float64, 'watch': watch                   1.000000
reset_B                 0.374432
ttl_thirdQ              0.374031
packet_size_B_thirdQ    0.349233
packet_size_B_avg       0.325506
ttl_A_thirdQ            0.308538
ttl_A_min               0.308538
ttl_A_median            0.308538
ttl_A_max               0.308538
ttl_A_firstQ            0.308538
Name: watch, dtype: float64, 'water_sensor': water_sensor                   1.000000
ttl_min                        0.364884
ttl_firstQ                     0.363620
B_port_is_8080                 0.353626
ds_field_B                     0.350548
packet_inter_arrivel_firstQ    0.350330
packet_inter_arrivel_min       0.342999
packet_inter_arrivel_median    0.341444
packet_inter_arrivel_A_min     0.328024
packets_A_B_ratio              0.323405
Name: water_sensor, dtype: float64}

In [86]:
# Get all unique feature names across all categories
features = set()
for i in range(len(categories)):
    top_corr = corr_per_category_top[i]
    if categories[i] in top_corr.index:
        top_corr = top_corr.drop(categories[i])
    features.update(top_corr.index)
features = list(features)
# order elements of all_features alphabetically
features.sort()
print(features)
print(len(features))

['B_port_is_11095', 'B_port_is_8080', 'domain_is_else', 'ds_field_B', 'http_count_host', 'http_count_req_content_type', 'http_count_resp_content_type', 'http_count_user_agents', 'http_has_req_content_type', 'http_has_resp_content_type', 'http_has_user_agent', 'is_http', 'packet_inter_arrivel_A_min', 'packet_inter_arrivel_B_min', 'packet_inter_arrivel_firstQ', 'packet_inter_arrivel_median', 'packet_inter_arrivel_min', 'packet_size_A_avg', 'packet_size_A_stdev', 'packet_size_A_thirdQ', 'packet_size_A_var', 'packet_size_B_avg', 'packet_size_B_entropy', 'packet_size_B_thirdQ', 'packets_A_B_ratio', 'reset', 'reset_A', 'reset_B', 'ssl_count_client_ciphersuites', 'ssl_dom_server_name_alexaRank', 'ssl_ratio_client_elliptic_curves', 'ssl_req_bytes_stdev', 'ttl_A_avg', 'ttl_A_firstQ', 'ttl_A_max', 'ttl_A_median', 'ttl_A_min', 'ttl_A_thirdQ', 'ttl_B_avg', 'ttl_B_firstQ', 'ttl_B_max', 'ttl_B_median', 'ttl_B_min', 'ttl_B_stdev', 'ttl_B_thirdQ', 'ttl_entropy', 'ttl_firstQ', 'ttl_max', 'ttl_median', 'ttl_min', 'ttl_stdev', 'ttl_thirdQ', 'ttl_var']
53

In [88]:
# create a dictionary with the elements of all_features as keys that contains the number of occurrences of each element in the list corr_per_category_top
feature_prevalence = {feature: 0 for feature in features}
for i in range(len(categories)):
    top_corr = corr_per_category_top[i]
    if categories[i] in top_corr.index:
        top_corr = top_corr.drop(categories[i])
    for feature in top_corr.index:
        feature_prevalence[feature] += 1
print(feature_prevalence)

{'B_port_is_11095': 1, 'B_port_is_8080': 3, 'domain_is_else': 1, 'ds_field_B': 3, 'http_count_host': 1, 'http_count_req_content_type': 1, 'http_count_resp_content_type': 1, 'http_count_user_agents': 1, 'http_has_req_content_type': 1, 'http_has_resp_content_type': 1, 'http_has_user_agent': 1, 'is_http': 1, 'packet_inter_arrivel_A_min': 3, 'packet_inter_arrivel_B_min': 1, 'packet_inter_arrivel_firstQ': 3, 'packet_inter_arrivel_median': 3, 'packet_inter_arrivel_min': 3, 'packet_size_A_avg': 1, 'packet_size_A_stdev': 1, 'packet_size_A_thirdQ': 1, 'packet_size_A_var': 1, 'packet_size_B_avg': 1, 'packet_size_B_entropy': 1, 'packet_size_B_thirdQ': 1, 'packets_A_B_ratio': 1, 'reset': 1, 'reset_A': 1, 'reset_B': 2, 'ssl_count_client_ciphersuites': 1, 'ssl_dom_server_name_alexaRank': 1, 'ssl_ratio_client_elliptic_curves': 1, 'ssl_req_bytes_stdev': 1, 'ttl_A_avg': 2, 'ttl_A_firstQ': 4, 'ttl_A_max': 3, 'ttl_A_median': 4, 'ttl_A_min': 4, 'ttl_A_thirdQ': 4, 'ttl_B_avg': 1, 'ttl_B_firstQ': 1, 'ttl_B_max': 1, 'ttl_B_median': 2, 'ttl_B_min': 1, 'ttl_B_stdev': 1, 'ttl_B_thirdQ': 1, 'ttl_entropy': 2, 'ttl_firstQ': 3, 'ttl_max': 2, 'ttl_median': 2, 'ttl_min': 3, 'ttl_stdev': 1, 'ttl_thirdQ': 2, 'ttl_var': 1}

In [89]:
feature_corr_sum = {
    feature: sum(
        corr_per_category[category][feature]
        for category in range(len(categories))
        if feature in corr_per_category[category]
    )
    for feature in features
}
print(feature_corr_sum)

{'B_port_is_11095': 1.389501493255388, 'B_port_is_8080': 2.919231274741209, 'domain_is_else': 1.6345162598439504, 'ds_field_B': 2.895271529101306, 'http_count_host': 1.6287570854605373, 'http_count_req_content_type': 1.6287570854605373, 'http_count_resp_content_type': 1.6038172371216128, 'http_count_user_agents': 1.6287570854605373, 'http_has_req_content_type': 1.6287570854605373, 'http_has_resp_content_type': 1.6287570854605373, 'http_has_user_agent': 1.6287570854605373, 'is_http': 1.6287570854605373, 'packet_inter_arrivel_A_min': 2.7930045648305786, 'packet_inter_arrivel_B_min': 1.074807629398935, 'packet_inter_arrivel_firstQ': 2.906054256049794, 'packet_inter_arrivel_median': 2.8061393593210444, 'packet_inter_arrivel_min': 2.9027666830075507, 'packet_size_A_avg': 1.0808871311697275, 'packet_size_A_stdev': 1.3977990836263052, 'packet_size_A_thirdQ': 1.1161194721968493, 'packet_size_A_var': 1.278753706365447, 'packet_size_B_avg': 1.5647548563930362, 'packet_size_B_entropy': 1.8127397658684066, 'packet_size_B_thirdQ': 1.5709625046913347, 'packets_A_B_ratio': 2.658857175685626, 'reset': 2.13834334627139, 'reset_A': 1.8096586980814913, 'reset_B': 1.5104015338660344, 'ssl_count_client_ciphersuites': 1.3118008650608015, 'ssl_dom_server_name_alexaRank': 2.068101936619495, 'ssl_ratio_client_elliptic_curves': 0.7957541444704151, 'ssl_req_bytes_stdev': 1.3089334181649712, 'ttl_A_avg': 3.15085921556549, 'ttl_A_firstQ': 3.15085921556549, 'ttl_A_max': 3.15085921556549, 'ttl_A_median': 3.15085921556549, 'ttl_A_min': 3.15085921556549, 'ttl_A_thirdQ': 3.15085921556549, 'ttl_B_avg': 1.8639761362246043, 'ttl_B_firstQ': 1.7905688329153937, 'ttl_B_max': 1.8800000722525447, 'ttl_B_median': 1.7975328189484165, 'ttl_B_min': 1.5739637905689052, 'ttl_B_stdev': 1.450634838388696, 'ttl_B_thirdQ': 1.8766289649610273, 'ttl_entropy': 2.662128662365806, 'ttl_firstQ': 2.921562158923922, 'ttl_max': 2.3424292899461894, 'ttl_median': 3.015210297022297, 'ttl_min': 2.9285824735075434, 'ttl_stdev': 2.2012711580599227, 'ttl_thirdQ': 2.469505509603161, 'ttl_var': 2.0494364207675586}

In [96]:
feature_groups = {
    'B_port': [feature for feature in features if feature.startswith('B_port')],
    'http': [feature for feature in features if feature.startswith('http') or feature == 'is_http'],
    'packet_inter': [feature for feature in features if feature.startswith('packet_inter')],
    'packet_size': [feature for feature in features if feature.startswith('packet_size')],
    'reset': [feature for feature in features if feature.startswith('reset')],
    'ssl': [feature for feature in features if feature.startswith('ssl')],
    'ttl_A': [feature for feature in features if feature.startswith('ttl_A')],
    'ttl_B': [feature for feature in features if feature.startswith('ttl_B')],
    'ttl_others': [feature for feature in features if feature.startswith('ttl_') and feature not in ['ttl_A', 'ttl_B']],
    'others': []
}
# put all elements of features that are not in the above groups into 'others'
for feature in features:
    if feature not in feature_groups['B_port'] and feature not in feature_groups['http'] and feature not in feature_groups['packet_inter'] and feature not in feature_groups['packet_size'] and feature not in feature_groups['reset'] and feature not in feature_groups['ssl'] and feature not in feature_groups['ttl_A'] and feature not in feature_groups['ttl_B'] and feature not in feature_groups['ttl_others']:
        feature_groups['others'].append(feature)
print(feature_groups)
print(feature_groups['others'])

{'B_port': ['B_port_is_11095', 'B_port_is_8080'], 'http': ['http_count_host', 'http_count_req_content_type', 'http_count_resp_content_type', 'http_count_user_agents', 'http_has_req_content_type', 'http_has_resp_content_type', 'http_has_user_agent', 'is_http'], 'packet_inter': ['packet_inter_arrivel_A_min', 'packet_inter_arrivel_B_min', 'packet_inter_arrivel_firstQ', 'packet_inter_arrivel_median', 'packet_inter_arrivel_min'], 'packet_size': ['packet_size_A_avg', 'packet_size_A_stdev', 'packet_size_A_thirdQ', 'packet_size_A_var', 'packet_size_B_avg', 'packet_size_B_entropy', 'packet_size_B_thirdQ'], 'reset': ['reset', 'reset_A', 'reset_B'], 'ssl': ['ssl_count_client_ciphersuites', 'ssl_dom_server_name_alexaRank', 'ssl_ratio_client_elliptic_curves', 'ssl_req_bytes_stdev'], 'ttl_A': ['ttl_A_avg', 'ttl_A_firstQ', 'ttl_A_max', 'ttl_A_median', 'ttl_A_min', 'ttl_A_thirdQ'], 'ttl_B': ['ttl_B_avg', 'ttl_B_firstQ', 'ttl_B_max', 'ttl_B_median', 'ttl_B_min', 'ttl_B_stdev', 'ttl_B_thirdQ'], 'ttl_others': ['ttl_A_avg', 'ttl_A_firstQ', 'ttl_A_max', 'ttl_A_median', 'ttl_A_min', 'ttl_A_thirdQ', 'ttl_B_avg', 'ttl_B_firstQ', 'ttl_B_max', 'ttl_B_median', 'ttl_B_min', 'ttl_B_stdev', 'ttl_B_thirdQ', 'ttl_entropy', 'ttl_firstQ', 'ttl_max', 'ttl_median', 'ttl_min', 'ttl_stdev', 'ttl_thirdQ', 'ttl_var'], 'others': ['domain_is_else', 'ds_field_B', 'packets_A_B_ratio']}
['domain_is_else', 'ds_field_B', 'packets_A_B_ratio']

In [97]:
feature_group_prevalence = {
    group: sum(feature_prevalence[feature] for feature in features)
    for group, features in feature_groups.items()
}
print(feature_group_prevalence)

{'B_port': 4, 'http': 8, 'packet_inter': 13, 'packet_size': 7, 'reset': 4, 'ssl': 4, 'ttl_A': 21, 'ttl_B': 8, 'ttl_others': 45, 'others': 5}

In [98]:
feature_group_corr_sum = {
    group: sum(
        feature_corr_sum[feature]
        for feature in features
    )
    for group, features in feature_groups.items()
}
print(feature_group_corr_sum)

{'B_port': 4.308732767996597, 'http': 13.005116835345373, 'packet_inter': 12.482772492607902, 'packet_size': 9.822016520311106, 'reset': 5.458403578218915, 'ssl': 5.484590364315682, 'ttl_A': 18.90515529339294, 'ttl_B': 12.233305454259588, 'ttl_others': 51.72858671784893, 'others': 7.188644964630882}

In [99]:
feature_group_prevalence_density = {
    group: feature_group_prevalence[group] / len(features)
    for group, features in feature_groups.items()
}
print(feature_group_prevalence_density)

{'B_port': 2.0, 'http': 1.0, 'packet_inter': 2.6, 'packet_size': 1.0, 'reset': 1.3333333333333333, 'ssl': 1.0, 'ttl_A': 3.5, 'ttl_B': 1.1428571428571428, 'ttl_others': 2.142857142857143, 'others': 1.6666666666666667}

In [100]:
feature_group_corr_sum_density = {
    group: feature_group_corr_sum[group] / len(features)
    for group, features in feature_groups.items()
}
print(feature_group_corr_sum_density)

{'B_port': 2.1543663839982985, 'http': 1.6256396044181716, 'packet_inter': 2.49655449852158, 'packet_size': 1.403145217187301, 'reset': 1.819467859406305, 'ssl': 1.3711475910789206, 'ttl_A': 3.15085921556549, 'ttl_B': 1.7476150648942268, 'ttl_others': 2.4632660341832824, 'others': 2.396214988210294}

<h3>Interactive widgets to explore feature importance</h3>

In [ ]:
# make a dataframe with the data in feature_prevalence and append a column with the data in feature_corr_sum
feature_analysis = pd.DataFrame.from_dict(feature_prevalence, orient='index', columns=['prevalence'])
feature_analysis.index.name = 'feature'
feature_analysis.reset_index(inplace=True)
feature_analysis['corr_sum'] = feature_analysis['feature'].map(feature_corr_sum)
feature_analysis.head()

           feature  prevalence  corr_sum
0  B_port_is_11095           1  1.389501
1   B_port_is_8080           3  2.919231
2   domain_is_else           1  1.634516
3       ds_field_B           3  2.895272
4  http_count_host           1  1.628757

In [103]:
feature_analysis['corr_avg'] = feature_analysis['corr_sum'] / feature_analysis['prevalence']

In [104]:
feature_analysis['group'] = feature_analysis['feature'].map(
    lambda x: next((group for group, features in feature_groups.items() if x in features), 'others')
)

In [118]:
feature_analysis

,feature,prevalence,corr_sum,corr_avg,group
0,B_port_is_11095,1,1.389501,1.389501,B_port
1,B_port_is_8080,3,2.919231,0.973077,B_port
2,domain_is_else,1,1.634516,1.634516,others
3,ds_field_B,3,2.895272,0.965091,others
4,http_count_host,1,1.628757,1.628757,http
5,http_count_req_content_type,1,1.628757,1.628757,http
6,http_count_resp_content_type,1,1.603817,1.603817,http
7,http_count_user_agents,1,1.628757,1.628757,http
8,http_has_req_content_type,1,1.628757,1.628757,http
9,http_has_resp_content_type,1,1.628757,1.628757,http
10,http_has_user_agent,1,1.628757,1.628757,http
11,is_http,1,1.628757,1.628757,http
12,packet_inter_arrivel_A_min,3,2.793005,0.931002,packet_inter
13,packet_inter_arrivel_B_min,1,1.074808,1.074808,packet_inter
14,packet_inter_arrivel_firstQ,3,2.906054,0.968685,packet_inter
15,packet_inter_arrivel_median,3,2.806139,0.935380,packet_inter
16,packet_inter_arrivel_min,3,2.902767,0.967589,packet_inter
17,packet_size_A_avg,1,1.080887,1.080887,packet_size
18,packet_size_A_stdev,1,1.397799,1.397799,packet_size
19,packet_size_A_thirdQ,1,1.116119,1.116119,packet_size
20,packet_size_A_var,1,1.278754,1.278754,packet_size
21,packet_size_B_avg,1,1.564755,1.564755,packet_size
22,packet_size_B_entropy,1,1.812740,1.812740,packet_size
23,packet_size_B_thirdQ,1,1.570963,1.570963,packet_size
24,packets_A_B_ratio,1,2.658857,2.658857,others
25,reset,1,2.138343,2.138343,reset
26,reset_A,1,1.809659,1.809659,reset
27,reset_B,2,1.510402,0.755201,reset
28,ssl_count_client_ciphersuites,1,1.311801,1.311801,ssl
29,ssl_dom_server_name_alexaRank,1,2.068102,2.068102,ssl
30,ssl_ratio_client_elliptic_curves,1,0.795754,0.795754,ssl
31,ssl_req_bytes_stdev,1,1.308933,1.308933,ssl
32,ttl_A_avg,2,3.150859,1.575430,ttl_A
33,ttl_A_firstQ,4,3.150859,0.787715,ttl_A
34,ttl_A_max,3,3.150859,1.050286,ttl_A
35,ttl_A_median,4,3.150859,0.787715,ttl_A
36,ttl_A_min,4,3.150859,0.787715,ttl_A
37,ttl_A_thirdQ,4,3.150859,0.787715,ttl_A
38,ttl_B_avg,1,1.863976,1.863976,ttl_B
39,ttl_B_firstQ,1,1.790569,1.790569,ttl_B
40,ttl_B_max,1,1.880000,1.880000,ttl_B
41,ttl_B_median,2,1.797533,0.898766,ttl_B
42,ttl_B_min,1,1.573964,1.573964,ttl_B
43,ttl_B_stdev,1,1.450635,1.450635,ttl_B
44,ttl_B_thirdQ,1,1.876629,1.876629,ttl_B
45,ttl_entropy,2,2.662129,1.331064,ttl_others
46,ttl_firstQ,3,2.921562,0.973854,ttl_others
47,ttl_max,2,2.342429,1.171215,ttl_others
48,ttl_median,2,3.015210,1.507605,ttl_others
49,ttl_min,3,2.928582,0.976194,ttl_others
50,ttl_stdev,1,2.201271,2.201271,ttl_others
51,ttl_thirdQ,2,2.469506,1.234753,ttl_others
52,ttl_var,1,2.049436,2.049436,ttl_others

In [106]:
import plotly.express as px

In [124]:
fig_corr = px.sunburst(
    feature_analysis, 
    path=['group', 'feature'], 
    values='corr_sum',
    color='corr_avg', color_continuous_scale='Blues',
    title='Feature importance'
    )
fig_corr.show()